#ifndef RESOURCE_H
#define RESOURCE_H

#ifndef MIN_CODE_VERSION
	#define MIN_CODE_VERSION          "1.0"
#endif

#ifndef MAX_CODE_VERSION
	#define MAX_CODE_VERSION          "1.2"
#endif

#define PRODUCT_NAME 				 "HE1 Mod Loader"
#define VERSION_MAJOR 				 3
#define VERSION_MINOR 				 0
#define VERSION_REVISION 			 0
#define VERSION_BUILD 				 0

#define TOSTRING2(ARG) #ARG
#define TOSTRING(ARG) TOSTRING2(ARG)

#define VERSION_FULL VERSION_MAJOR,VERSION_MINOR,VERSION_REVISION,VERSION_BUILD
#define VERSION_STRING TOSTRING(VERSION_MAJOR) "." TOSTRING(VERSION_MINOR) "." TOSTRING(VERSION_REVISION) "." TOSTRING(VERSION_BUILD)

#define MIN_CODE_VERSION_KEY            101
#define MAX_CODE_VERSION_KEY            102

#define VS_VERSION_INFO 			    1

#endif
